Devour Tweak 2.0
ColonialMarines-Mirror/ColonialMarines-2018 pull request #453
Opened 2018-10-11 00:58 UTC by Surrealaser

-Devoured marines are now blinded for the duration of the devour, allowing aliens the opportunity to deposit them in unrecognizable locations.

-Devour delay now scales inversely with the pain the victim is in; the higher the pain (i.e. they're less able to resist), the faster it is completed, with a current max delay of 20 seconds vs a full health/no pain marine, and a minimum delay of 3 seconds. The delay is reduced by 1 second per 10 pain.

2018-10-11 05:16 UTC, subject217 commented
fetish content

2018-10-15 16:05 UTC, Rohesie commented
Conflicts as expected.

2018-10-15 22:32 UTC, Rohesie requested changes

2018-10-15 22:32 UTC, Rohesie commented on code/modules/mob/mob_grab.dm
> +		if(do_after(X, min(30, 200 - pulled.traumatic_shock), FALSE, 5, BUSY_ICON_HOSTILE)) //Devour delay scales inversely with victim's pain; 20 seconds max, 3 seconds min
I think you want here a `max(30, 200- pulled.traumatic_shock)`, no? `CLAMP` would be safer.

2018-10-16 15:56 UTC, Rohesie requested changes

2018-10-16 15:56 UTC, Rohesie commented on code/modules/mob/living/carbon/carbon_helpers.dm
> +/mob/living/carbon/proc/unvore_forced(var/mob/living/carbon/Xenomorph/X)
This seems to overlap with `unvore()` with a `forced` flag.

2018-10-16 15:56 UTC, Rohesie commented on code/modules/mob/living/carbon/xenomorph/XenoProcs.dm
> +/mob/living/carbon/Xenomorph/proc/empty_gut()
This overlaps as well.

2018-12-18 03:53 UTC, closed without merging